package app.app.samplekmp.app.profile.domain

import app.app.samplekmp.app.profile.data.ProfileEntity
import app.app.samplekmp.app.profile.data.UserEntity

data class User(val userId: String,
                val username: String,
                val gallery: List<String>,
                val typeAccountId: Int,
                val email: String,
                val firebaseId: String,
                val deviceToken: String,
                val verify: Int,
                val status: Int,
                val lastConnection: String,
                val latitude: Double,
                val longitude: Double,
                val city: String,
                val country: String,
                val codeCountry: String,
                var gender: Int,
                val searchGender: Int,
                val birthday: String,
                val zodiac: Int,
                val profile: Profile)

data class Profile(val situation: String,
                   val target: String,
                   val height: String,
                   val sport: String,
                   val bodyType: String,
                   val drink: String,
                   val smoke: String,
                   val occupation: String,
                   val company: String,
                   val goals: String,
                   val children: String,
                   val description: String,
                   val education: String,
                   val tattoo: String,
                   val religion: String,
                   val political: String)

fun User.toUserEntity() = UserEntity(
    userId = userId.toInt(),
    username = username,
    typeAccountId = typeAccountId,
    email = email,
    firebaseId = firebaseId,
    deviceToken = deviceToken,
    verify = verify,
    status = status,
    lastConnection = lastConnection,
    latitude = latitude,
    longitude = longitude,
    city = city,
    country = country,
    codeCountry = codeCountry,
    gender = gender,
    searchGender = searchGender,
    birthday = birthday,
    zodiac = zodiac,
    profileEntity = profile.toProfileEntity())

fun Profile.toProfileEntity() = ProfileEntity(
    situation = situation,
    target = target,
    height = height,
    sport = sport,
    bodyType = bodyType,
    drink = drink,
    smoke = smoke,
    occupation = occupation,
    company = company,
    goals = goals,
    children = children,
    description = description,
    education = education,
    tattoo = tattoo,
    religion = religion,
    political = political)
